### ISSUE TITLE
not able to install ioncube

### ISSUE THREAD

**Issue by keithbmcd** [dlanileonardo/opsworks-cookbooks#1]
Hi,

It fails at "/etc/php5/apache2/conf.d/00-ioncube.ini" -

template "/etc/php5/apache2/conf.d/00-ioncube.ini" do
  source 'ioncube.ini.erb'
end

May I know how can I fix it?

Thanks

**Comment by dlanileonardo** [comment]
Do you have the error message? What version of chef you use?
